/**
 * !!! DO NOT EDIT THIS FILE !!!
 */

import {
  addAListInDomFromAnArrayOfObjects,
  addElementsInDOM,
  getElementFromDomAndChangeColorToRed,
} from "./dom/dom.js"
import { userList } from "./datas.js"
import { addEventToDomOnClick, reactToClickEvent } from "./events/clicks.js"
import {
  addElementsInListOnEnterKey,
  displayInputContentInAlertOnEnterKey,
  removeElementsFromListWhenClicked,
} from "./events/inputs.js"
import {
  changesOnInputEvents,
  hoverFocusAndBlur,
  mouseMovements,
} from "./events/movements.js"
import { fetchDataOnClick } from "./fetch/fetchData.js"

console.log("JavaScrip started")

getElementFromDomAndChangeColorToRed()
addElementsInDOM()
addAListInDomFromAnArrayOfObjects(userList)
reactToClickEvent()
addEventToDomOnClick()
displayInputContentInAlertOnEnterKey()
addElementsInListOnEnterKey()
removeElementsFromListWhenClicked()
mouseMovements()
hoverFocusAndBlur()
changesOnInputEvents()
fetchDataOnClick()
